### PR TITLE
Secure build scripts

### PR DESCRIPTION
**Pull request by anandthakker**

### CODE REVIEW

**Comment by anandthakker** [comment]
cc @danielfdsilva @scisco

**Comment by danielfdsilva** [comment]
@anandthakker we don't actually need a gh token on this repo since it's never deployed. Everything else is fine

**Comment by anandthakker** [comment]
Ah, right.

**Comment by kamicut** [comment]
@danielfdsilva @anandthakker I'd think keep it, we can make the splash index page some quick links to docs and deploy that.

**Pull request merged**
