### PR TITLE
Fail tests on lint errors.

### PR DESCRIPTION
**Pull request by anandthakker**
I think it makes sense to include linting as part of automated testing: since we've agreed on a code style, I think it makes sense to have each person be responsible for their own commits preserving that style.  Otherwise, we get into a situation where a few lint errors creep in, and then we end up having to choose between cleaning these up in future commits--which just adds noise to the diffs--or leaving them in and possibly adding more (since, now that my editor is giving me errors, it's hard to distinguish between mine and pre-existing ones).

### CODE REVIEW

**Comment by jflasher** [comment]
It's so ironic that this PR failed because of linting! ;)

**Comment by jflasher** [comment]
I have mixed feelings on this one. In a nice stable world, I am totally for it. However, when things get rushed, I fear it. If we're trying to deploy something very quickly, the last thing I want is for the build to fail because we're missing a ; somewhere. But I do agree that if it's not enforced, the linting becomes somewhat meaningless.

**Comment by anandthakker** [comment]
@jflasher Good point.  Updated it so that for deploy-branch pushes, the linting will not balk.

**Comment by jflasher** [comment]
@anandthakker Thank you for pandering to my fears. :) :+1:

**Pull request merged**
