### PR TITLE
Feat/vendor js

### PR DESCRIPTION
**Pull request by anandthakker**
cc @jflasher

### CODE REVIEW

**Comment by jflasher** [comment]
@anandthakker Looks great, ran it quickly and it does what I think it's supposed to do. :)

Two things, could you update the README with an example or callout of how to use the feature so we don't forget?

Also, when I change package.json, Gulp is rebuilding vendor.js (as I'd expect) but then it's also rebuilding bundle.js but I'm not sure why?

```
[09:23:59] Starting 'vendorScripts'...
[09:23:59] Finished 'vendorScripts' after 6.83 ms
[BS] 2 files changed (vendor.js.map, vendor.js)
[09:23:59] 1541 bytes written (0.00 seconds)
[BS] 2 files changed (bundle.js.map, bundle.js)
```

**Comment by anandthakker** [comment]
@jflasher - good point on the README, will do.

And yeah, that is indeed strange that it's rebuilding the app bundle.  I'll take a quick look at that too.

**Comment by anandthakker** [comment]
@jflasher udpated the readme.  Also, I think the reason that the app bundle gets built when `packages.json` changes may be that we call `b.external()` to tell browserify which packages not to include in the bundle.  I'd say we just let this fly, since rebuilding the app bundle should be really small/quick anyway, compared to the vendor bundle.

**Comment by jflasher** [comment]
@anandthakker agreed, don't think it'll be a huge deal.

**Pull request merged**
