### PR TITLE
Use environment-based config.

### LINKED ISSUE #14: Figure out how to utilize env/build variables
For example, we have a site that deploys to staging and production and needs to grab data from a data url and it should point to the staging or production data url where appropriate. I had thought to use something like https://github.com/developmentseed/developmentseed.github.com/blob/publish/gulpfile.js#L254 and then hook up [gulp-replace](https://github.com/lazd/gulp-replace) to do a string replace. It works for a build, but looks a little ugly and things start to get worse when considering how to hook this up with `serve` (versus `build`). I may have been overcomplicating it a bit since this shouldn't be too hard?

### PR DESCRIPTION
**Pull request by anandthakker**
Closes #14 

This needs to be tested on Travis, but @jflasher can you give it a quick review before I do that?

### CODE REVIEW

**Comment by jflasher** [comment]
@anandthakker :+1:. Think we should add a watcher on the config files to regenerate if they change?

**Comment by anandthakker** [comment]
Heh, I had that in there, but then realized that since we're only copying
over if config.js doesn't exist, it didn't do anything. I think that makes
sense though, because we want to be able to preserve our local config
options. I guess the other way would be to have config.js always be a
direct copy, and use local.js to override it...

**Comment by jflasher** [comment]
What about a config.local.js?

**Comment by anandthakker** [comment]
@jflasher yeah that works

**Comment by anandthakker** [comment]
@jflasher Updated the strategy a bit in the above commit

**Comment by jflasher** [comment]
@anandthakker added some info to the README, go ahead and merge in if you think it looks good. :+1: :heart_eyes:

**Pull request merged**
